// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// HTTPClient is an autogenerated mock type for the HTTPClient type
type HTTPClient struct {
	mock.Mock
}

// Post provides a mock function with given fields: url, key, value
func (_m *HTTPClient) Post(url string, key string, value string) (*http.Response, error) {
	ret := _m.Called(url, key, value)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, string, string) *http.Response); ok {
		r0 = rf(url, key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(url, key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
