version: '3'

services:
  webderver:
    container_name: webserver
    image: scratch
    build: .
    command: /bin/shorten -mode webserver
    volumes:
      - ./shorten:/bin/shorten
      - ./html:/bin/html
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    ports:
      - "8080:8080"
    environment:
      HTML: "/bin/html"
      PORT: "8080"
  server:
    container_name: server
    image: scratch
    build: .
    command: /bin/shorten -mode server
    volumes:
      - ./bin/shorten:/bin/shorten
    networks:
      app_net:
        ipv4_address: 172.20.0.5

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24