// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "text/plain"
  ],
  "produces": [
    "text/plain"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "URL Shortener API",
    "version": "1.0"
  },
  "paths": {
    "/redirect/{hash}": {
      "get": {
        "summary": "Redirect from short URL to long URL.",
        "operationId": "redirect",
        "parameters": [
          {
            "$ref": "#/parameters/hash"
          }
        ],
        "responses": {
          "302": {
            "description": "Redirection to long URL."
          },
          "404": {
            "description": "Shortened URL not found."
          }
        }
      }
    },
    "/shorten": {
      "post": {
        "summary": "Create short URL.",
        "operationId": "shorten",
        "parameters": [
          {
            "description": "Node pool to be created.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Body"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Body"
            }
          },
          "500": {
            "description": "Internal error."
          }
        }
      }
    }
  },
  "definitions": {
    "Body": {
      "type": "object",
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "hash": {
      "type": "string",
      "description": "URL ID hash.",
      "name": "hash",
      "in": "path",
      "required": true
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "text/plain"
  ],
  "produces": [
    "text/plain"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "URL Shortener API",
    "version": "1.0"
  },
  "paths": {
    "/redirect/{hash}": {
      "get": {
        "summary": "Redirect from short URL to long URL.",
        "operationId": "redirect",
        "parameters": [
          {
            "type": "string",
            "description": "URL ID hash.",
            "name": "hash",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "302": {
            "description": "Redirection to long URL."
          },
          "404": {
            "description": "Shortened URL not found."
          }
        }
      }
    },
    "/shorten": {
      "post": {
        "summary": "Create short URL.",
        "operationId": "shorten",
        "parameters": [
          {
            "description": "Node pool to be created.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Body"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Body"
            }
          },
          "500": {
            "description": "Internal error."
          }
        }
      }
    }
  },
  "definitions": {
    "Body": {
      "type": "object",
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "hash": {
      "type": "string",
      "description": "URL ID hash.",
      "name": "hash",
      "in": "path",
      "required": true
    }
  }
}`))
}
