// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "text/plain"
  ],
  "produces": [
    "text/plain"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "URL Shortener API",
    "version": "1.0"
  },
  "paths": {
    "/shorten": {
      "post": {
        "summary": "Create short URL.",
        "parameters": [
          {
            "name": "url",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "short_url": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Internal error."
          }
        }
      }
    },
    "/{hash}": {
      "get": {
        "summary": "Redirect from short URL to long URL.",
        "parameters": [
          {
            "type": "string",
            "description": "URL ID hash.",
            "name": "hash",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "302": {
            "description": "Redirection to long URL."
          },
          "404": {
            "description": "Shortened URL not found."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "text/plain"
  ],
  "produces": [
    "text/plain"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "URL Shortener API",
    "version": "1.0"
  },
  "paths": {
    "/shorten": {
      "post": {
        "summary": "Create short URL.",
        "parameters": [
          {
            "name": "url",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "short_url": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Internal error."
          }
        }
      }
    },
    "/{hash}": {
      "get": {
        "summary": "Redirect from short URL to long URL.",
        "parameters": [
          {
            "type": "string",
            "description": "URL ID hash.",
            "name": "hash",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "302": {
            "description": "Redirection to long URL."
          },
          "404": {
            "description": "Shortened URL not found."
          }
        }
      }
    }
  }
}`))
}
