swagger: '2.0'
info:
  title: URL Shortener API
  version: '1.0'
schemes:
  - http
consumes:
  - text/plain
produces:
  - text/plain

paths:
  /{hash}:
    get:
      summary: Redirect from short URL to long URL.
      parameters:
        - in: path
          name: hash
          required: true
          type: string
          description: URL ID hash.
      responses:
        302:
          description: Redirection to long URL.
        404:
          description: Shortened URL not found.

  /shorten:
    post:
      summary: Create short URL.
      parameters:
        - name: body
          required: true
          in: body
          description: Node pool to be created.
          schema:
            $ref: '#/definitions/Body'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Body'
        500:
          description: Internal error.

definitions:
  Body:
    type: object
    properties:
      url:
        type: string
    required:
      - url