// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shorten.proto

package grpcapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShortenRequest struct {
	LongUrl              string   `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenRequest) Reset()         { *m = ShortenRequest{} }
func (m *ShortenRequest) String() string { return proto.CompactTextString(m) }
func (*ShortenRequest) ProtoMessage()    {}
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b277664a2543c5f, []int{0}
}

func (m *ShortenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenRequest.Unmarshal(m, b)
}
func (m *ShortenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenRequest.Marshal(b, m, deterministic)
}
func (m *ShortenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenRequest.Merge(m, src)
}
func (m *ShortenRequest) XXX_Size() int {
	return xxx_messageInfo_ShortenRequest.Size(m)
}
func (m *ShortenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenRequest proto.InternalMessageInfo

func (m *ShortenRequest) GetLongUrl() string {
	if m != nil {
		return m.LongUrl
	}
	return ""
}

type ShortenResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenResponse) Reset()         { *m = ShortenResponse{} }
func (m *ShortenResponse) String() string { return proto.CompactTextString(m) }
func (*ShortenResponse) ProtoMessage()    {}
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b277664a2543c5f, []int{1}
}

func (m *ShortenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenResponse.Unmarshal(m, b)
}
func (m *ShortenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenResponse.Marshal(b, m, deterministic)
}
func (m *ShortenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenResponse.Merge(m, src)
}
func (m *ShortenResponse) XXX_Size() int {
	return xxx_messageInfo_ShortenResponse.Size(m)
}
func (m *ShortenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenResponse proto.InternalMessageInfo

func (m *ShortenResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RedirectURLRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectURLRequest) Reset()         { *m = RedirectURLRequest{} }
func (m *RedirectURLRequest) String() string { return proto.CompactTextString(m) }
func (*RedirectURLRequest) ProtoMessage()    {}
func (*RedirectURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b277664a2543c5f, []int{2}
}

func (m *RedirectURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectURLRequest.Unmarshal(m, b)
}
func (m *RedirectURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectURLRequest.Marshal(b, m, deterministic)
}
func (m *RedirectURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectURLRequest.Merge(m, src)
}
func (m *RedirectURLRequest) XXX_Size() int {
	return xxx_messageInfo_RedirectURLRequest.Size(m)
}
func (m *RedirectURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectURLRequest proto.InternalMessageInfo

func (m *RedirectURLRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RedirectURLResponse struct {
	LongUrl              string   `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectURLResponse) Reset()         { *m = RedirectURLResponse{} }
func (m *RedirectURLResponse) String() string { return proto.CompactTextString(m) }
func (*RedirectURLResponse) ProtoMessage()    {}
func (*RedirectURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b277664a2543c5f, []int{3}
}

func (m *RedirectURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectURLResponse.Unmarshal(m, b)
}
func (m *RedirectURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectURLResponse.Marshal(b, m, deterministic)
}
func (m *RedirectURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectURLResponse.Merge(m, src)
}
func (m *RedirectURLResponse) XXX_Size() int {
	return xxx_messageInfo_RedirectURLResponse.Size(m)
}
func (m *RedirectURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectURLResponse proto.InternalMessageInfo

func (m *RedirectURLResponse) GetLongUrl() string {
	if m != nil {
		return m.LongUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*ShortenRequest)(nil), "grpcapi.ShortenRequest")
	proto.RegisterType((*ShortenResponse)(nil), "grpcapi.ShortenResponse")
	proto.RegisterType((*RedirectURLRequest)(nil), "grpcapi.RedirectURLRequest")
	proto.RegisterType((*RedirectURLResponse)(nil), "grpcapi.RedirectURLResponse")
}

func init() { proto.RegisterFile("shorten.proto", fileDescriptor_8b277664a2543c5f) }

var fileDescriptor_8b277664a2543c5f = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xce, 0xc8, 0x2f,
	0x2a, 0x49, 0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x2a, 0x48, 0x4e,
	0x2c, 0xc8, 0x54, 0xd2, 0xe6, 0xe2, 0x0b, 0x86, 0xc8, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0x49, 0x72, 0x71, 0xe4, 0xe4, 0xe7, 0xa5, 0xc7, 0x97, 0x16, 0xe5, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0xb1, 0x83, 0xf8, 0xa1, 0x45, 0x39, 0x4a, 0xaa, 0x5c, 0xfc, 0x70, 0xc5, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x19, 0x89, 0xc5, 0x19, 0x50, 0x95, 0x60,
	0xb6, 0x92, 0x06, 0x97, 0x50, 0x50, 0x6a, 0x4a, 0x66, 0x51, 0x6a, 0x72, 0x49, 0x68, 0x90, 0x0f,
	0xcc, 0x5c, 0x6c, 0x2a, 0x0d, 0xb8, 0x84, 0x51, 0x54, 0x42, 0x0d, 0xc5, 0xed, 0x04, 0xa3, 0x19,
	0x8c, 0x70, 0x07, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xd9, 0x70, 0xb1, 0x43, 0x45,
	0x84, 0xc4, 0xf5, 0xa0, 0xfe, 0xd2, 0x43, 0xf5, 0x94, 0x94, 0x04, 0xa6, 0x04, 0xd4, 0x2e, 0x0f,
	0x2e, 0x6e, 0x24, 0x27, 0x08, 0x49, 0xc3, 0x15, 0x62, 0x7a, 0x41, 0x4a, 0x06, 0xbb, 0x24, 0xc4,
	0xa4, 0x24, 0x36, 0x70, 0xd0, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x60, 0x20, 0x03, 0x0f,
	0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShortenServiceClient is the client API for ShortenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenServiceClient interface {
	Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error)
	RedirectURL(ctx context.Context, in *RedirectURLRequest, opts ...grpc.CallOption) (*RedirectURLResponse, error)
}

type shortenServiceClient struct {
	cc *grpc.ClientConn
}

func NewShortenServiceClient(cc *grpc.ClientConn) ShortenServiceClient {
	return &shortenServiceClient{cc}
}

func (c *shortenServiceClient) Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error) {
	out := new(ShortenResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.ShortenService/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenServiceClient) RedirectURL(ctx context.Context, in *RedirectURLRequest, opts ...grpc.CallOption) (*RedirectURLResponse, error) {
	out := new(RedirectURLResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.ShortenService/RedirectURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenServiceServer is the server API for ShortenService service.
type ShortenServiceServer interface {
	Shorten(context.Context, *ShortenRequest) (*ShortenResponse, error)
	RedirectURL(context.Context, *RedirectURLRequest) (*RedirectURLResponse, error)
}

// UnimplementedShortenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShortenServiceServer struct {
}

func (*UnimplementedShortenServiceServer) Shorten(ctx context.Context, req *ShortenRequest) (*ShortenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}
func (*UnimplementedShortenServiceServer) RedirectURL(ctx context.Context, req *RedirectURLRequest) (*RedirectURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedirectURL not implemented")
}

func RegisterShortenServiceServer(s *grpc.Server, srv ShortenServiceServer) {
	s.RegisterService(&_ShortenService_serviceDesc, srv)
}

func _ShortenService_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenServiceServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.ShortenService/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenServiceServer).Shorten(ctx, req.(*ShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenService_RedirectURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenServiceServer).RedirectURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.ShortenService/RedirectURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenServiceServer).RedirectURL(ctx, req.(*RedirectURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShortenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.ShortenService",
	HandlerType: (*ShortenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _ShortenService_Shorten_Handler,
		},
		{
			MethodName: "RedirectURL",
			Handler:    _ShortenService_RedirectURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shorten.proto",
}
