// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/ixoja/shorten/internal/service"
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostShortenOKCode is the HTTP code returned for type PostShortenOK
const PostShortenOKCode int = 200

/*PostShortenOK OK

swagger:response postShortenOK
*/
type PostShortenOK struct {

	/*
	  In: Body
	*/
	Payload *service.PostShortenOKBody `json:"body,omitempty"`
}

// NewPostShortenOK creates PostShortenOK with default headers values
func NewPostShortenOK() *PostShortenOK {

	return &PostShortenOK{}
}

// WithPayload adds the payload to the post shorten o k response
func (o *PostShortenOK) WithPayload(payload *service.PostShortenOKBody) *PostShortenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post shorten o k response
func (o *PostShortenOK) SetPayload(payload *service.PostShortenOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShortenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostShortenInternalServerErrorCode is the HTTP code returned for type PostShortenInternalServerError
const PostShortenInternalServerErrorCode int = 500

/*PostShortenInternalServerError Internal error.

swagger:response postShortenInternalServerError
*/
type PostShortenInternalServerError struct {
}

// NewPostShortenInternalServerError creates PostShortenInternalServerError with default headers values
func NewPostShortenInternalServerError() *PostShortenInternalServerError {

	return &PostShortenInternalServerError{}
}

// WriteResponse to the client
func (o *PostShortenInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
