// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi URL Shortener API

    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0

    Consumes:
    - text/plain

    Produces:
    - text/plain

swagger:meta
*/
package restapi
